splash = false

wallpaper {
    monitor = HDMI-A-1
    path = ~/.config/wallpaper/1.jpg
    fit_mode = cover
}

# wallpaper {
#     monitor = HDMI-A-1
#     path = ~/.config/wallpaper/2.png
#     fit_mode = cover
# }
