splash = false

# wallpaper {
#     monitor = HDMI-A-1
#     path = ~/.config/wallpaper/1.jpg
#     fit_mode = cover
# }

# wallpaper {
#     monitor = HDMI-A-1
#     path = ~/.config/wallpaper/2.png
#     fit_mode = cover
# }

# wallpaper {
#     monitor = HDMI-A-1
#     path = ~/.config/wallpaper/3.png
#     fit_mode = cover
# }

# wallpaper {
#     monitor = HDMI-A-1
#     path = ~/.config/wallpaper/4.jpg
#     fit_mode = cover
# }

# wallpaper {
#     monitor = HDMI-A-1
#     path = ~/.config/wallpaper/5.png
#     fit_mode = cover
# }

wallpaper {
    monitor = HDMI-A-1
    path = ~/.config/wallpaper/6.png
    fit_mode = cover
}
